"""Pytest configuration and shared fixtures for Apple ingest tests."""

import pytest
from .fixtures import (
    MockEKEvent,
    MockEKReminder,
    MockMailMessage,
    MockFileMetadata,
    calendar_event_simple,
    calendar_event_with_attendees,
    calendar_event_all_day,
    calendar_event_invalid_times,
    calendar_event_no_title,
    reminder_task_simple,
    reminder_task_with_due_date,
    reminder_task_completed,
    reminder_task_today,
    reminder_task_no_status,
    mail_message_simple,
    mail_message_flagged,
    mail_message_no_sender,
    file_markdown_note,
    file_document,
    file_invalid_path,
    calendar_event_batch,
    reminder_task_batch,
    mail_message_batch,
    file_metadata_batch,
    full_ingest_data,
    invalid_ingest_data,
)

__all__ = [
    "MockEKEvent",
    "MockEKReminder",
    "MockMailMessage",
    "MockFileMetadata",
    "calendar_event_simple",
    "calendar_event_with_attendees",
    "calendar_event_all_day",
    "calendar_event_invalid_times",
    "calendar_event_no_title",
    "reminder_task_simple",
    "reminder_task_with_due_date",
    "reminder_task_completed",
    "reminder_task_today",
    "reminder_task_no_status",
    "mail_message_simple",
    "mail_message_flagged",
    "mail_message_no_sender",
    "file_markdown_note",
    "file_document",
    "file_invalid_path",
    "calendar_event_batch",
    "reminder_task_batch",
    "mail_message_batch",
    "file_metadata_batch",
    "full_ingest_data",
    "invalid_ingest_data",
]
