#!/usr/bin/env python3
"""
AUTOGENERATED FROM .kgc – DO NOT EDIT MANUALLY.

This KGCT (KGC Technician) CLI is generated from RDF in .kgc/ontology.ttl
and rendered via Jinja template .kgc/projections/cli.py.j2.

To modify commands, edit .kgc/ontology.ttl and re-run:
    python -m personal_kgcl.generators.cli_generator

Generated: 2025-11-25T09:04:45.745472+00:00
From: /Users/sac/dev/kgcl/.kgc/cli.ttl
"""

import sys
from pathlib import Path
from typing import List, Optional

import typer

# Import handlers from personal_kgcl.handlers
try:
    from personal_kgcl.handlers.docs import generate_agenda
except ImportError as e:
    print(f"Warning: Could not import docs.generate_agenda: {e}", file=sys.stderr)
try:
    from personal_kgcl.handlers.codegen import generate_cli
except ImportError as e:
    print(f"Warning: Could not import codegen.generate_cli: {e}", file=sys.stderr)
try:
    from personal_kgcl.handlers.ingest import scan_apple
except ImportError as e:
    print(f"Warning: Could not import ingest.scan_apple: {e}", file=sys.stderr)
try:
    from personal_kgcl.handlers.validation import validate_ingest
except ImportError as e:
    print(f"Warning: Could not import validation.validate_ingest: {e}", file=sys.stderr)


# CLI App Definition
app = typer.Typer(
    name="kgct",
    help="KGC Technician Console (macOS/iOS personal fabric)",
    rich_markup_mode="rich",
    no_args_is_help=True,
)

# ============================================================================
# COMMANDS (auto-generated from RDF)
# ============================================================================


@app.command(name="generate-agenda")
def generate_agenda(
    day: str = typer.Option(
        None, "--day", help="Which day to generate (today, tomorrow, this-week)"
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose output"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Simulate without making changes"
    ),
):
    """
    Render agenda projection for a day or week.


    """
    try:
        # Build kwargs from provided args
        kwargs = {"day": day, "verbose": verbose, "dry_run": dry_run}

        # Remove None values
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        # Call handler
        result = generate_agenda(**kwargs)

        if result is not None:
            typer.echo(result)

    except KeyboardInterrupt:
        typer.echo("\nAborted.", err=True)
        sys.exit(1)
    except Exception as e:
        if verbose:
            import traceback

            traceback.print_exc()
        else:
            typer.echo(f"Error: {e!s}", err=True)
        sys.exit(1)


@app.command(name="generate-cli")
def generate_cli(
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose output"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Simulate without making changes"
    ),
):
    """
    Regenerate Typer CLI from .kgc/cli.ttl + Jinja template.


    """
    try:
        # Build kwargs from provided args
        kwargs = {"verbose": verbose, "dry_run": dry_run}

        # Remove None values
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        # Call handler
        result = generate_cli(**kwargs)

        if result is not None:
            typer.echo(result)

    except KeyboardInterrupt:
        typer.echo("\nAborted.", err=True)
        sys.exit(1)
    except Exception as e:
        if verbose:
            import traceback

            traceback.print_exc()
        else:
            typer.echo(f"Error: {e!s}", err=True)
        sys.exit(1)


@app.command(name="scan-apple")
def scan_apple(
    source: str | None = typer.Option(
        None,
        "--source",
        help="Subset of sources to ingest (calendars, reminders, mail, files)",
    ),
    input: str | None = typer.Option(
        None, "--input", help="Path to JSON payload exported from PyObjC ingest bridge"
    ),
    output: str | None = typer.Option(
        None,
        "--output",
        help="Override output Turtle path (default from apple.ingest.ttl)",
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose output"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Simulate without making changes"
    ),
):
    """
    Ingest Calendar/Reminders/Mail/File data via PyObjC or structured JSON.


    """
    try:
        # Build kwargs from provided args
        kwargs = {
            "source": source,
            "input": input,
            "output": output,
            "verbose": verbose,
            "dry_run": dry_run,
        }

        # Remove None values
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        # Call handler
        result = scan_apple(**kwargs)

        if result is not None:
            typer.echo(result)

    except KeyboardInterrupt:
        typer.echo("\nAborted.", err=True)
        sys.exit(1)
    except Exception as e:
        if verbose:
            import traceback

            traceback.print_exc()
        else:
            typer.echo(f"Error: {e!s}", err=True)
        sys.exit(1)


@app.command(name="validate-data")
def validate_data(
    input: str | None = typer.Option(
        None, "--input", help="Path to Turtle/N3 graph to validate"
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose output"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Simulate without making changes"
    ),
):
    """
    Run SHACL/ASK validation for ingested RDF.


    """
    try:
        # Build kwargs from provided args
        kwargs = {"input": input, "verbose": verbose, "dry_run": dry_run}

        # Remove None values
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        # Call handler
        result = validate_ingest(**kwargs)

        if result is not None:
            typer.echo(result)

    except KeyboardInterrupt:
        typer.echo("\nAborted.", err=True)
        sys.exit(1)
    except Exception as e:
        if verbose:
            import traceback

            traceback.print_exc()
        else:
            typer.echo(f"Error: {e!s}", err=True)
        sys.exit(1)


# ============================================================================
# CALLBACK (runs before any command)
# ============================================================================


@app.callback(invoke_without_command=True)
@app.callback()
def main(
    ctx: typer.Context,
    version: bool = typer.Option(False, "--version", help="Show version"),
):
    """
    KGC Technician Console (macOS/iOS personal fabric).

    KGC Technician Console for personal macOS/iOS productivity fabric.
    All operations driven by RDF ontology in .kgc/
    """
    if version:
        typer.echo("0.0.0")
        raise typer.Exit()


# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    app()
